### ISSUE TITLE
Definir frameworks de testes 

### ISSUE THREAD

**Issue by valescamoura** [valescamoura/chess#7]
- [ ] Testar ferramenta integrada ao Django (https://www.digitalocean.com/community/tutorials/how-to-add-unit-testing-to-your-django-project-pt).

**Comment by karinaplemos** [comment]
Ferramentas de testes escolhidas:
Back-> Pytest e Front->Selenium

**Comment by karinaplemos** [comment]
Ferramentas de testes escolhidas:
Back-> Pytest e Front->Selenium

Plano de testes será elaborado nas próximas sprints.
